# Generated by Django 5.0.1 on 2024-01-31 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addjob',
            name='Application_Deadline',
            field=models.DateField(max_length=100),
        ),
    ]
