# Generated by Django 5.0.1 on 2024-01-31 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_addjob_application_deadline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addjob',
            old_name='Job_Title',
            new_name='myJob_Title',
        ),
    ]
