# Generated by Django 5.0.1 on 2024-01-31 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_addjob_addjobtable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addjobtable',
            name='Application_Deadline',
            field=models.DateTimeField(max_length=100),
        ),
    ]
