# Generated by Django 4.2.9 on 2024-02-02 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_addjobtable_application_deadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_Name', models.CharField(max_length=100)),
                ('Credit_Hour', models.IntegerField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudentTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_Name', models.CharField(max_length=100)),
                ('Student_Department', models.CharField(max_length=100)),
                ('Courses', models.ManyToManyField(to='myapp.coursetable')),
            ],
        ),
        migrations.CreateModel(
            name='MarksTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Marks', models.IntegerField()),
                ('CGPA', models.IntegerField()),
                ('Course_Name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.coursetable')),
                ('Student_Name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.studenttable')),
            ],
        ),
        migrations.CreateModel(
            name='GradeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CGPA', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.markstable')),
                ('Student_Name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.studenttable')),
            ],
        ),
    ]
