# Generated by Django 4.2.6 on 2024-02-04 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_coursetable_course_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradetable',
            name='Grade_sum',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coursetable',
            name='Credit_Hour',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='studenttable',
            name='Courses',
            field=models.ManyToManyField(to='myapp.coursetable'),
        ),
    ]
