# Generated by Django 4.2.6 on 2024-02-04 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_gradetable_grade_sum_alter_coursetable_credit_hour_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradetable',
            name='CGPA',
        ),
    ]
