# Generated by Django 4.2.6 on 2024-02-04 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_gradetable_cgpa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markstable',
            name='CGPA',
            field=models.FloatField(null=True),
        ),
    ]
