# Generated by Django 4.2.6 on 2024-02-04 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_markstable_cgpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttable',
            name='Gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studenttable',
            name='Student_Age',
            field=models.IntegerField(null=True),
        ),
    ]
