# Generated by Django 4.2.6 on 2024-02-04 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_markstable_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markstable',
            name='Grade',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
