# Generated by Django 4.2.6 on 2024-02-06 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_markstable_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='markstable',
            name='credit',
            field=models.IntegerField(null=True),
        ),
    ]
